### ISSUE TITLE
Oh damn, you forgot my username in the students.csv file? : /

### ISSUE THREAD

**Issue by AlesCavalcante** [StuntsPT/pr_bio_2023-2024_assignments#15]
Please, if you can, fix this in the students.csv file.

**Comment by StuntsPT** [comment]
I won't since you fixed it yourself via [f39870d](https://github.com/StuntsPT/pr_bio_2023-2024_assignments/pull/16/commits/f39870d9ac7cd6af4452181f2a2977d038d963e8). =-)
